algoritmo "Exercício 2"
// Função :
// Autor :
// Data : 29/04/2021
// Seção de Declarações 
var
valor:inteiro
valor2: inteiro
resultado: inteiro
inicio
escreval("Digite o primeiro valor")
leia(valor)
escreval("digite o segundo valor")
leia(valor2)
resultado <- valor + valor2

se(resultado > 10) entao
escreval("O valor da soma é maior que 10!")
senao
escreval("O valor da soma é menor que 10!")
fimse

fimalgoritmo
