algoritmo "Exercício 4 - Valores em ordem"
// Função :
// Autor :
// Data : 04/05/2021
// Seção de Declarações 
var
valor: inteiro
valorDois: inteiro
inicio
escreval("Digite o 1º valor")
leia(valor)
escreval("Digite o 2º valor")
leia(valorDois)
se(valor > valorDois) entao
escreval("1º valor ",valor," 2º valor ", valorDois)
senao
escreval("2º valor ",valorDois, " 1º valor ", valor)
fimse
fimalgoritmo
