algoritmo "Exemplo de looping com caracteres"
// Função :
// Autor :
// Data : 04/05/2021
// Seção de Declarações 
var
letra: caracter
inicio
escreval("Digite uma letra")
leia(letra)

enquanto letra <> "s" faca
escreval("Você não digitou a letra correta! Está preso no meu fluxo infinito")
escreval("digite a nova letra")
leia(letra)
fimenquanto

escreval("Você saiu do meu fluxo infinito!")

fimalgoritmo
