algoritmo "Exemplo Laço Enquanto"
// Função :
// Autor :
// Data : 04/05/2021
// Seção de Declarações 
var
contadora: inteiro
inicio
//contadora <- 10
leia(contadora)
//enquanto contadora <= 10 faca
//escreval(contadora)
//contadora <- contadora + 1 Incremento + 1
//fimenquanto

enquanto contadora >= 0 faca
escreval(contadora)
contadora <- contadora - 1 //Decremento - 1
fimenquanto


fimalgoritmo
