algoritmo "Exercício 02 - Enquanto com valor 0"
// Função :
// Autor :
// Data : 10/05/2021
// Seção de Declarações
var
valor: real
valorDois: real
inicio
escreval("Digite o 1º valor")
leia(valor)
escreval("Digite o 2º valor")
leia(valorDois)

enquanto valorDois = 0 faca
   escreval("Valor Inválido!")
   escreval("Digite o 2º valor")
   leia(valorDois)
fimenquanto

escreval("O resultado da divisão é ", (valor / valorDois))

fimalgoritmo
