algoritmo "Exemplo 1 - Uso de vetores"
// Função :
// Autor :
// Data : 05/05/2021
// Seção de Declarações 
var
//id : vetor [inicial .. final] de tipo_de_dado
nomes: vetor[1..3] de caracter
inicio
escreval("Digite o 1º nome")
leia(nomes[1])
escreval("Digite o 2º nome")
leia(nomes[2])
escreval("Digite o 3º nome")
leia(nomes[3])

escreval("O 1º nome é ",nomes[1], " o 2º nome é ",nomes[2], " o 3º nome é ",nomes[3])



fimalgoritmo
