algoritmo "Exercício 01 - Lista VII"
// Função :
// Autor :
// Data : 11/05/2021
// Seção de Declarações 
var
numeros : vetor [1..5] de inteiro
contadora, soma:inteiro
inicio
para contadora de 1 ate 5 faca
escreval("Digite os valores do vetor")
leia(numeros[contadora])
soma <- soma + numeros[contadora]
fimpara

escreval("A soma dos valores do vetor são ",soma)

para contadora de 1 ate 5 faca
escreval("Os valores digitados são ",numeros[contadora])
fimpara

fimalgoritmo
