algoritmo "Aula 03 - Estruturas de Decisão"
// Função :
// Autor :
// Data : 28/04/2021
// Seção de Declarações 
var
numero: inteiro
inicio
escreval("Digite um número")
leia(numero)

se (numero > 10) entao
 escreval("O numero ", numero, " é maior que 10!")
 senao
 se (numero < 10) entao
    escreval("O numero ",numero, " é menor que 10!")
 senao
    escreval("O número", numero, " é igual a 10!")
 fimse
fimse

fimalgoritmo
