algoritmo "semnome"
// Função :
// Autor :
// Data : 28/04/2021
// Seção de Declarações 
var
caneta: caracter
inicio
caneta <- "azul"

//Simples
se(caneta = "azul") entao
escreval("A caneta é Azul!") // Só executa se for verdade
fimse

//Composta
se (caneta = "preta") entao
escreval("É caneta é preta!")
senao
escreval("A caneta não é preta!") // Se a primeira comparação não for Verdadeira
fimse

fimalgoritmo
