algoritmo "Exemplo de função sem parâmetro"
// Função :
// Autor :
// Data : 10/05/2021
// Seção de Declarações

funcao teste():caracter
inicio
retorne "Estamos usando função"
fimfuncao

funcao somar():inteiro
inicio
retorne 1 + 1
fimfuncao

funcao multiplicar() : inteiro
var
x,y:inteiro

inicio
x <- 4
y <- 2

retorne x * y
fimfuncao

var

inicio

escreval(teste())
escreval(somar())
escreval("O resultado da multiplicação é ", multiplicar())

fimalgoritmo
